import { Layout } from '@/src/components/layout/Layout'
import { ProductPagesTemplate } from '../components/templates/ProductPagesTemplate'

export default function ForLLMs() {
    const data = {
        seoTitle:
            'Hubql for LLMs - AI-Ready Documentation and Context Generation',
        seoDescription:
            'Hubql helps developers create AI-ready documentation and generate structured context for Large Language Models (LLMs), improving workflows and accuracy.',
    }

    const content = {
        title: 'Hubql for LLMs - Elevating Documentation for AI',
        description:
            'Hubql empowers developers to bridge the gap between APIs and intelligent systems by generating high-quality context and documentation for LLMs like ChatGPT, Claude, and Copilot.',
        tryNowUrl: '/docs/quickstarts/get-started',
        meetingUrl: 'https://go.hubql.com/www-for-llms',
        // videoTitle: 'API Client Demo',
        // videoDescription:
        //     'Watch a short demo (2min) of the Hubql Client to get a quick overview of its features.',
        // videoUrl: 'https://www.youtube.com/watch?v=KAsjv4w66Yo',
        ctaButtonText: 'Generate AI-Ready Docs',
        ctaButtonUrl: '/docs/quickstarts/get-started',
        ctaTitle: 'Ready?',
        ctaDescription:
            'Streamline your API documentation and prepare your projects for the age of AI with Hubql.',
        faqs: [
            {
                title: 'What is llms.txt and how does it work?',
                description:
                    'llms.txt is a structured file format generated by Hubql to provide LLMs with API-specific context, enhancing their ability to interact with your codebase.',
            },
            {
                title: 'How does Hubql help LLMs?',
                description:
                    'Hubql generates Markdown summaries of your project, offering structured insights that improve LLM responses and accuracy.',
            },
            {
                title: 'Why is documentation important for AI agents?',
                description:
                    'Documentation ensures that both developers and AI tools can effectively understand and utilize APIs, reducing errors and increasing efficiency.',
            },
            {
                title: 'Can Hubql work with any LLM?',
                description:
                    'Yes, Hubql-generated outputs are designed to be LLM-agnostic, making them compatible with tools like ChatGPT, Claude, and GitHub Copilot.',
            },
            {
                title: 'Is Hubql open source?',
                description: `Yes, Hubql is open source, offering flexibility and transparency for teams and organizations of all sizes.`,
            },
            {
                title: 'What types of projects benefit from this?',
                description: `Any project using APIs or requiring LLM integration can benefit, including SaaS platforms, AI-powered applications, and enterprise tools.`,
            },
        ],
        section: [
            {
                title: 'Why LLMs Need Context',
                imageUrl: '/product-page/llms.svg',
                description:
                    'LLMs like ChatGPT and GPT-4 rely on high-quality context to generate accurate and relevant responses. Without structured and concise information, even the most advanced AI struggles to deliver optimal results. Hubql bridges this gap by enabling developers to generate precise API context through the hubql context command, ensuring both human and AI agents have the knowledge they need to succeed.',
            },
            {
                title: 'APIs as the Backbone of AI Agents',
                imageUrl: '/product-page/ai-agent.svg',
                description:
                    'APIs are fundamental to AI agents, acting as the gateways for data exchange and interaction. High-quality API documentation ensures that both human developers and AI tools can interact with APIs efficiently. With Hubql’s automated documentation generation and llms.txt support, you can ensure your APIs are always LLM-ready.',
            },
            {
                title: 'How Hubql Bridges the Gap',
                imageUrl: '/product-page/documentation.svg',
                description: (
                    <div>
                        Hubql generates Markdown summaries of your codebase,
                        optimized for LLMs. These summaries provide:
                        <ul>
                            <li>High-level overviews of your project.</li>
                            <li>
                                Key files, dependencies, and their
                                relationships.
                            </li>
                            <li>
                                Structured context that enhances LLM
                                understanding and outputs. By making this
                                context available in formats like llms.txt,
                                Hubql empowers developers to integrate LLMs
                                seamlessly into their workflows.
                            </li>
                        </ul>
                    </div>
                ),
            },
            {
                title: 'Best Practices for Optimizing LLM Outputs',
                imageUrl: '/product-page/optimizing.svg',
                description: (
                    <div>
                        To get the most out of LLMs, providing structured,
                        clean, and focused context is essential. Hubql
                        simplifies this by:
                        <ul>
                            <li>
                                Ensuring your documentation and summaries are
                                always up-to-date.
                            </li>
                            <li>
                                Generating focused insights that prevent noise
                                in LLM outputs.
                            </li>
                            <li>
                                Offering tools like llms.txt to guide AI tools
                                effectively.With Hubql, you’re not just
                                preparing your APIs for developers—you’re
                                preparing them for intelligent systems.
                            </li>
                        </ul>
                    </div>
                ),
            },
        ],
    }
    return (
        <Layout data={data}>
            <ProductPagesTemplate content={content} />
        </Layout>
    )
}
